In [1]:
%load_ext autoreload
%autoreload 2
from nbodysim.Simulator import Simulator
from nbodysim.Analyzer import Analyzer
from nbodysim.Utils import periapsisFinder
import numpy as np

In [ ]:
sim1 = Simulator(name='Sun-Mercury',notebook=True)

In [ ]:
peri = 46.002e9
maxSpeed = 58.98e3

mPos = [-peri,0,0]
mVel = [0,-maxSpeed,0]

In [ ]:
sim1.addObject(name="Sun",mass=1.989e30,radius=696.34e6,color=(239,142,56))
sim1.addObject(name="Mercury",mass=3.285e23,radius=2.43e6,position=mPos,velocity=mVel,color=(219,206,202))

In [ ]:
for i in range(2000):
    sim1.step(dt=10,numberOfSteps=60*6,save=True)

In [ ]:
ana = Analyzer("Sun-Mercury")
ana.plot(["Mercury",'Mercury'],['x','y'])

In [2]:
sim2 = Simulator(name='Saturn-Titan')

sim2.addObject(name='Saturn',mass=5.683e26,radius=58.232e6,color=(250,229,191))

pos, vel = periapsisFinder(5.683e26,1221e6,.0292,.33)
sim2.addObject(name='Titan',mass=1.345e20,radius=2575e3,position=pos,velocity=vel,color=(0,0,0))

Loading BokehJS ...

In [3]:
sim2.play(dt=10,numberOfSteps=60*6,save=True,axes=('x','y'),pause=.01,)

No step function specified, defaulting to Euler.
Stopped


In [4]:
print(sim2.getObject("Titan").position)

[[-1.1522248e+09 -2.8522291e+08 -6.6363865e+06]
 [-1.1553499e+09 -2.7188301e+08 -6.6543870e+06]
 [-1.1597751e+09 -2.5172326e+08 -6.6798735e+06]
 [-1.1638588e+09 -2.3148958e+08 -6.7033965e+06]
 [-1.1676013e+09 -2.1118787e+08 -6.7249480e+06]
 [-1.1709989e+09 -1.9082411e+08 -6.7445215e+06]
 [-1.1740534e+09 -1.7040416e+08 -6.7621100e+06]
 [-1.1767608e+09 -1.4993405e+08 -6.7777090e+06]
 [-1.1791236e+09 -1.2941988e+08 -6.7913125e+06]
 [-1.1811375e+09 -1.0886761e+08 -6.8029165e+06]
 [-1.1828047e+09 -8.8283296e+07 -6.8125170e+06]
 [-1.1841229e+09 -6.7672992e+07 -6.8201125e+06]
 [-1.1850929e+09 -4.7042796e+07 -6.8256985e+06]
 [-1.1857138e+09 -2.6398766e+07 -6.8292730e+06]
 [-1.1859852e+09 -5.7469620e+06 -6.8308360e+06]
 [-1.1859078e+09  1.4906519e+07 -6.8303870e+06]
 [-1.1854798e+09  3.5555588e+07 -6.8279270e+06]
 [-1.1847036e+09  5.6194168e+07 -6.8234560e+06]
 [-1.1835780e+09  7.6816168e+07 -6.8169745e+06]
 [-1.1821041e+09  9.7415528e+07 -6.8084840e+06]
 [-1.1802821e+09  1.1798619e+08 -6.79798

In [5]:
ana2 = Analyzer('Saturn-Titan',notebook=True)
ana2.plot(['Titan','Titan','Titan'],['vx','vy','vz'])

Loading BokehJS ...

Figure(id='1493', ...)

In [ ]:
test = np.array([["sim"]*10,list(range(10))])
test = np.swapaxes(test,0,1)
print(test[0])