In [19]:
%load_ext autoreload
%autoreload 2
from nbodysim.Simulator import Simulator
from nbodysim.Analyzer import Analyzer
from nbodysim.Utils import periapsisFinder
import numpy as np

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [20]:
sim1 = Simulator(name='Sun-Mercury',notebook=True)

Loading BokehJS ...

In [50]:
peri = 46.002e9
maxSpeed = 58.98e3

mPos = [peri,0,0]
mVel = [0,maxSpeed,0]

In [51]:
theta = np.pi/2
rotate = np.array([[np.cos(theta),-np.sin(theta),0],[np.sin(theta),np.cos(theta),0],[0,0,1]])
rotate = np.round_(rotate,decimals=5)
print(rotate.dot(mPos))
print(rotate.dot(mVel))

[0.0000e+00 4.6002e+10 0.0000e+00]
[-58980.      0.      0.]


In [35]:
print(newPos)

[-4.6002e+10  0.0000e+00  0.0000e+00]


In [23]:
sim1.addObject(name="Sun",mass=1.989e30,radius=696.34e6,color=(239,142,56))
sim1.addObject(name="Mercury",mass=3.285e23,radius=2.43e6,position=mPos,velocity=mVel,color=(219,206,202))

In [24]:
sim1.play(dt=10,numberOfSteps=60*6,save=True,plotFirst=True,axes=('x','y'),plotRange=None,trails=True)

No step function specified, defaulting to Euler.
Stopped


In [ ]:
ana = Analyzer("Sun-Mercury")
ana.plot(["Mercury",'Mercury'],['x','y'])

In [15]:
sim2 = Simulator(name='Saturn-Titan')

sim2.addObject(name='Saturn',mass=5.683e26,radius=58.232e6,color=(250,229,191))

pos, vel = periapsisFinder(5.683e26,1221e6,.0292,.33)
sim2.addObject(name='Titan',mass=1.345e20,radius=2575e3,position=pos,velocity=[0,0,0],color=(0,0,255))

Loading BokehJS ...

In [16]:
sim2.plot(axes=('x','y'),plotRange=None,plotSize=(600,600),trails=True)

In [17]:
sim2.play(dt=10,numberOfSteps=60*6,save=True,plotFirst=False)

No step function specified, defaulting to Euler.
5.683001345e+26 0
Stopped


In [18]:
ana2 = Analyzer('Saturn-Titan')
ana2.plot(['Titan','Saturn','Titan'],['vx','vy','vz'])

Loading BokehJS ...

Figure(id='9682', ...)